### ISSUE TITLE
client excessively read too many logs

### ISSUE THREAD

**Issue by drortirosh** [opengsn/gsn#119]
When searching for a relay to use for a transaction, the `RelayClient` scans for all relays that were added/refreshed recently, by searching for `RelayAdded` events.
The search, however, is done on ALL events from the relay, instead of only **RelayAdded** (and **RelayRemoved**) events.
As a consequence, the client actually get (and discards) all **TransactionRelayed** events.

This has performance issue, and potentially, if there are more than 1000 relayed transaction a day (yay!), it will completely break the client.

**What has to be done:**

The search is done in `ServerHelper.fetchRelaysAdded()`
- it should read only **RelayAdded** events (instead of allEvents)
- after processing those events, it should read **RelayRemoved**, and remove matching relays.

NOTE: a relay can't be added after its removed, so its OK to process all "added" events first, and then all "removed" events.

**Comment by drortirosh** [comment]
@spalladino : nice of you of referencing this issue (and fixing it) in your repo 
(https://github.com/OpenZeppelin/openzeppelin-gsn-provider/pull/28)
It would be nicer if you contribute bugfixes to the public GSN repo.

**Comment by spalladino** [comment]
@drortirosh we had started work on a fork of the GSN provider in the interest of time. We had the deadline of the Berlin blockchain week looming, and needed to ship a stable version of the entire stack before that. Given that our collaboration on the RelayHub had been slow due to several back-and-forths (yet very fruitful nonetheless), we had opted to work on our version of the codebase for the client in order to make it in time.

I was under the impression that this had been clearly communicated back in the day, but it seems it is not the case - my apologies for the misunderstanding.
