### ISSUE TITLE
RelayClient lookup limit cannot be configured

### ISSUE THREAD

**Issue by nventuro** [opengsn/gsn#226]
The client currently hardcodes the lookup limit in blocks to 6000, which means:

- the actual lookup time is network-dependent (some networks have blocktimes lower than 15s)
- the client will not work at all on networks such as Lightchain, where, queries that go over 5k blocks in the past hang)

**Comment by drortirosh** [comment]
its very problematic to have this lookup programatic: the client and `Relay` must use the same number - that's why its hard-coded in both.
in order NOT to hard-code it, it can be configured (at construction time) on the RelayHub.
both client and relay know the RH before making a call (the relay at startup, and the client gets the RH from the target contract)

**Comment by EnchanterIO** [comment]
@nventuro @drortirosh BTW, why is this behaviour necessary in first place? Why this information can't be queried from the RelayHub SC itself? What's the advantage of re-building the state by listening to logs?

**Comment by drortirosh** [comment]
If you look closely, the RelayHub doesn't even save the information the clients use to contact the relays - the url, txfee are merely broadcasted as events.
The `registerRelay` is a "do-nothing" in case the relay is already active (except emitting an event). This is important, since the relay has to call `registerRelay` periodically (daily), otherwise client's won't try to contact it.
Moreover, the client doesn't care about a specific relay, but all active relays. There's no easy way in solidity to have a data-structure of multiple entities (relays) that the client can easily query for "all".
All-in-all, events seemed like the most effective (both in terms of relay gas-price and client's API calls) to achieve this purpose.
