### ISSUE TITLE
Scaling up the Relays Network

### ISSUE THREAD

**Issue by drortirosh** [opengsn/gsn#232]
### The problem
The current design, each relay has exactly one address, and it put stake on it.
However, on real network, there is a change for a transaction to get stalled for a period of time.
During that time, the relay is unable to make more calls through this address.

This means that scaling up the network requires a huge amount of relays - and each relay (address) has to put a stake, which makes it very ineffective.

### Possible options for the relay:
* Always require higher gas price: The relay can require all transaction to be (say)  20% above current average. This might alleviate SOME of the problem, but with a side-effect of raising the current gas-price average (once a large # of transactions go through a relay)
* After a period of time, try to increase the gas price on a pending transaction. While it will release the transaction, the relay doesn't get compensated for this gas increase (the caller pays for the initial signed gas-price the relay accepted)
* The relay try to create new transaction with "future" nonce. These transaction would be delayed and processed AFTER the pending transaction, regardless of the gas-price they provide.
* The relay can have multiple addresses (essentially, appear as multiple relays) However, this would require stake on each of those addresses (in addition of maintaining eth balance for each of those addresses.
### Suggestion

Allow a relay to stake with multiple addresses. This means that
* the stake would be per *owner*, not per *relay*
* penalizing *any* of the relay addresses would slash the stake of the owner, rendering all those relays as "penalized"

**Comment by yoav-tabookey** [comment]
Multiple addresses with a shared staked owner seem like the best option IMHO. But make sure only the owner can add addresses, so attackers can't add an address to an owner and slash him. Maybe add an API for adding and removing addresses, associated with msg.sender.

**Comment by edukaded** [comment]
Another possibility and perhaps a simpler one would be to have the contract utilize tx.gasprice and pay that, regardless of the user's requested gas price.  They could then reprice stuck transactions as per normal.  It would then be up to the recipient contract to approve or decline the charge.  

After all it is the recipient contract which makes the payment, not the end user.  
It is entirely possible that someone utilizing the system may be willing to pay a premium to nodes to prioritize the transaction and get it in there faster.

Let me give you a use case we are working on.

We have a stablecoin (backed by ethers) that we want to be completely transparent and seamless to the user.  The user is always charged a flat % fee per transaction and we call the fee x.  The user is paying this by having x in stable coins deducted from their balance per transaction.  We then burn this and use it to subsidize gas to the relay nodes and using the excess to recapitalize the coin thereby providing stability and speed.

If transactions get "stuck", because the transaction cannot be easily repriced then it lowers the utility value of the coin and frankly reduces trust.  We would always want every transaction to clear in 1 minute or less and as a result we are willing to pay as much as it takes to get it done.

Honestly I would rather a node be focused on processing my transaction and only my transaction until the transaction is fully processed.  Having it expend resources to "help someone else in line behind me" while waiting for mine to complete, causes a competitive bid for attention that is detrimental to the end user experience in the same manner as the current gas market is detrimental.  

Meaning that if you have a relaynode able to shift it's attention somewhere else then the incentive on the relay is to throw as many transactions out there as it can and see what sticks, rather than focusing on getting them completed on a first come, first served basis.

**Comment by drortirosh** [comment]
1. the client determine the price, since its impossible for a contract to check the current gas price. We want to prevent malicious relays force excessive gas-price (as it gets compensated by % of it) We assume that the client is more aligned with the contract in that manner (the contract's vendor is usually the one who created the client)
2. if you have a mechanism on-chain to determine the current suggested gas-price, you can add it to your `acceptRelayedCall` , and thus completely reject transaction which has gas-price too low.
3. the client can prevent a relay from "stacking up" transactions, by specifying `allowed_relay_nonce_gap=1`, instead of default 3. This way, the client would immediately detect "stacking up", and re-issue the request through another relay. The relay's transaction would get rejected, since it replays the contract's nonce.

**Comment by drortirosh** [comment]
@nventuro , @spalladino : your comments?

**Comment by nventuro** [comment]
From my understanding, the `allowed_relay_nonce_gap` limit comes from two concerns:

1. a relayer doesn't want transactions to not be executed due to a previous stuck transaction
2. a relayer doesn't want to be too exposed to its transactions changing state in a recipient and causing `canRelay` to fail (the 'inconsistent accept' issue)

Given that 2. can also be caused by other relayers serving similar requests (or even the same one!), regular transactions being placed before the relayed one, among others, the only valid concern is 1. Scaling horizontally with multiple signing agents seems like a good idea, and it doesn't create any obvious problems. 

The only caveat is that we may want to limit the maximum number of signers per operation, to place an upper bound on the execution cost of a multi-signer penalization removal. Alternatively, a doubly linked approach could also work (owner to relayers, relayers to owner), where it is the owner that is penalized, and relayers are only valid if they belong to a non-penalized owner.

**Comment by drortirosh** [comment]
Actually, having multiple relay addresses would also address another issue, and that's reduced price for "keepalive" messasges:
Currently, a relay is required to use current market gasPrice for the periodic `registerRelay`. This is because it can't afford having that message block its address.
With multiple-addressesper-relay, a relay can send a ping with low gas price, and wait even 1-2 hours for it to get mined, since it has other addresses capable of sending out transactions.
