### ISSUE TITLE
postRelayedCallMaxGas is not enough

### ISSUE THREAD

**Issue by pertsev** [opengsn/gsn#234]
What should we do if `postRelayedCallMaxGas` is not enough for our contract?  [Take a look](https://github.com/peppersec/tornado-mixer/blob/gsn/contracts/ERC20Mixer.sol#L55-L78) - all we want to do is sell some user tokens on Uniswap in order to cover the GSN relayer's fee. 

`postRelayedCallMaxGas` is [100000](https://github.com/tabookey/tabookey-gasless/blob/master/contracts/RelayHub.sol#L49) while I need something like 200k or so.

It's clear why the hub has those hardcoded values as `postRelayedCallMaxGas`, `preRelayedCallMaxGas`, `acceptRelayedCallMaxGas` etc. The purpose is to be sure that `relayCall` itself never goes out of gas and relayer will be refunded in case of `(accept|pre|post)RelayedCall` failure. But it looks like it's still possible to have such behavior without hardcoding exact values. 

Here are my thoughts about it:
1) We can reserve some percentages of all supplied gas for `pre`, `post` and other needs. If so, all I need to do as a dapp developer is provide enough `gasLimit` with the transaction. But there is an issue with that - some projects can require different percentages and the increasing `gasLimit` more and more will hit the block gas limit for some project. Anyway, it's better than the current approach, it gives us some flexibility, right?
2) Why don't we allow a user (developer) to specify what amount of gas the hub should spend for each step? So the [`uint256 gasLimit`](https://github.com/tabookey/tabookey-gasless/blob/master/contracts/RelayHub.sol#L265) would be like `uint256[4] gasLimit` where 
```js
acceptRelayedCallMaxGas = gasLimit[0];
preRelayedCallMaxGas = gasLimit[1];
relayedCallMaxGas = gasLimit[2]
postRelayedCallMaxGas = gasLimit[3];
```

I think other things like [`gasOverhead`](https://github.com/tabookey/tabookey-gasless/blob/master/contracts/RelayHub.sol#L38-L44) can be left as are because they are known.

@nventuro what do you think about it?

**Comment by nventuro** [comment]
This limitation stems from us not being sure of what sort of logic would be included in `pre` and `post`, and there is sadly not much that can be done about it, other than wait for a v2 RelayHub (there are already a couple proposals for improvements already).

Your suggested option 2 is a fine idea, and is similar to one we had considered: instead of the user specifying gas for `accept`, `pre` and `post`, each _recipient contract_ could have a `gasLimits()` function that returned these values, since they should be constant for each recipient.

**Comment by rstormsf** [comment]
well, please keep us posted on when we can take it. Because it's major blocker for us at this moment and we won't be able to integrate into our application. We would still leave all the hooks in our contracts, so we could turn it on whenever you are ready. We would be happy to use and support Gas Station Network and keep feeding you our issues and feedback. 
Keep up the great work, and let us know! 

@nventuro

**Comment by rstormsf** [comment]
Actually we found a workaround about this by changing the way we can write our contract, so our hope is still there for mainnet integration and launch with GSN! stay tuned for updates.

**Comment by shahafn** [comment]
As @nventuro said, we discussed that but it requires several API changes that we're planning to add to the next RelayHub version. 
Keep in mind that when adding another external call to the recipient, it also needs to be protected from reverting, especially in `canRelay()`, when we get `acceptRelayedCallMaxGas` from the recipient.
