### ISSUE TITLE
Use WETH instead of RelayHub deposit

### ISSUE THREAD

**Issue by drortirosh** [opengsn/gsn#251]
Currently, a RelayRecipient has to deposit ETH into the RelayHub, in order to compensate a Relay for making a call. 
The contract's owner must either deposit a large amount, or periodically check if the amount is depleted, and put in more.

The problem is that a RelayHub can't control eth that belongs to another contract.

This proposal suggests that the RelayHub will use WETH instead, and the dapp just has to give the RelayHub *allowance* to use.
This way, a contract can give an allowance of (say) 10 WETH to the RelayHub, but still have that amount in its own acocunt.

**Comment by edukaded** [comment]
I thought everyone already just added a routine to the preflight function to check there is enough balance and then sweep ETH over.  How have you guys been doing it this whole time?

**Comment by edukaded** [comment]
Also how would your proposal work with contracts that are or have their own tokens?  Usually the allowance function is in TOKENS, ergo giving Relayhub an allowance would cause Relayhub to transfer tokens (WETH or whatever), instead of actual ETH.  If so that's cool but we need a way to let relayers know they are gonna be paid in someone's token rather than in ETH.

**Comment by drortirosh** [comment]
Its not for general token: Relays pay ETH for transactions, and thus must be compensated with ETH (wrapped eth is still good..)
If we allow paying directly in tokens, then we open the relay network for various attacks, as the relays now depend the current exchange rate.

We **DO** think that paying with tokens is a good thing - just its not the business of the relay server.
The relay is responsible of bringing transaction on-chain (eth-for-eth)
A **RelayRecipient** need to pay the relay - and can charge its real client for that - and that charge can be in tokens, where the RelayRecipient uniswaps it to ETH.

We actually had such demonstrations in ETHBerlin and ETHTlv: have a DAI-only address, which pays for creating its own proxy account, and then transfer DAI (or BAT) - all without eth - all with the help of a RelayRecipient to that eth/DAI conversions (we call this a "sponsor", since it sponsors the gas for the proxy account - even though it withdraws DAI from the account to pay for it)

**Comment by yoav-tabookey** [comment]
Right. RelayHub should stick to eth and avoid dealing with exchange rates. We already demonstrated a layer on top of GSN, that allows paying gas with tokens and exchanging then with eth.

But as for this proposal in general, I'm a bit worried about race conditions. When the deposit is kept by RelayHub, the relay can be confident that it'll get paid. If we use WETH, it's easier for situation to occur, where the WETH balance of the recipient will be depleted during the transaction, causing it to fail and revert. We could build some mechanism to protect against it, but it seems easier to mitigate with eth.

**Comment by drortirosh** [comment]
There are 2 strategies a RelayHub can take to make sure recipient pay for the transaction
(in both cases, the RelayHub must make sure there's enough balance in advance, and that it has an allowance to pull from it)

1. Use the standard pattern of pre-charge the max fee, and refund afterwards
2. In case that after the transaction there's not enough balance, it can REVERT the transaction in case there's no enough balance after the execution.

The former is the standard way, and also has the benefit of the client know its available balance
The latter makes less operations.

The current implementation is more aggressive: in case the client **modifies** its hub deposit - its transaction gets reverted, regardless if there's enough deposit left or not...

**Comment by yoav-tabookey** [comment]
The current deposit is single-purpose so there's no legitimate reason for the transaction to mess with it.  Hence it makes sense to revert if it changes.  But if we leave the deposit owned the recipient contract (as WETH), and the logic of the recipient also does something else with WETH, there could be situations where it gets depleted even by mistake.  Now the contract would have to take care to always leave enough balance to pay for the current transaction.

From the owner's perspective, the same work still has to be done, as there's a need to maintain sufficient WETH balance in the recipient, just like there's currently a need to maintain the ETH deposit in RelayHub.

From security perspective, the deposit also becomes more vulnerable.  Currently the deposit is exposed to bugs in RelayHub, allowing unauthorized withdrawal of a dapp's deposit.  Hopefully such bugs don't exist (although there's no formal proof).  With the new model, the deposit is exposed to any bug in the recipient contract (that may not have been designed to keep actual funds, if it's a non-financial contract for example, and it's still exposed to RelayHub bugs since there's an allowance.  Hence, the funds are potentially exposed to more bugs in this model.

We can definitely support this model as well, but let's consider the value it adds, compared to the tradeoffs above.
