### ISSUE TITLE
Increase usability with modifiers

### ISSUE THREAD

**Issue by edukaded** [opengsn/gsn#252]
I'd like to propose the addition of two modifiers, the purpose of these modifiers is to call out explicitly which calls will and will not be permitted via proxy.

For instance I have some maintenance functions that I really don't want proxied.  I also have some functions which I absolutely expect to be proxied.  Ergo the addition of two modifiers, proxyonly and noproxy (with the default being proxy allowed).

This will make security auditing a bit easier and allow designers to explicitly call out what functions can and cannot be proxied.

Just gathering thoughts before I try to submit another PR.

At this moment in time I'm considering just using a comparison of msg.sender == msgSender to determine if the function is being proxied.

**Comment by shahafn** [comment]
I think the modifier you were looking for is `relayHubOnly()` which is in `IRelayRecipient.sol`, or am I missing something?

**Comment by edukaded** [comment]
That seems like a strange thing.  How then do we ensure we are being called from RelayHub?  Or is that what the relayHubOnly modifier is for?

**Comment by shahafn** [comment]
The `relayHubOnly` modifier is meant to be used on `acceptRelayedCall, preRelayedCall and postRelayedCall`. This is indeed how we ensure we are called from `RelayHub` which should of course be configured in advance in the dapp (as `RelayRecipient`). Only in functions that call `relayHubOnly` we can safely call `getSender()`. Otherwise, any non-trusted caller can alter the address concatenated to end of `msg.data`.
