### ISSUE TITLE
Bug in the actual relayed call

### ISSUE THREAD

**Issue by igor-dulger** [opengsn/gsn#282]
Hi guys,
I believe you have a bug in this line 
https://github.com/openeth-dev/gsn/blob/db149eeb4694740f06c4041ecb641b3714a676af/contracts/RelayHub.sol#L418

This expression doesn't form a correct call data
 `abi.encodePacked(relayRequest.callData.encodedFunction, relayRequest.relayData.senderAccount)`
address must have 0 prefix, encodePacked will append it as it is
to fix this you should use 
`abi.encodePacked(relayRequest.callData.encodedFunction, abi.encode(relayRequest.relayData.senderAccount))`

**Comment by drortirosh** [comment]
We specified that the *last 20 bytes* are the address, not the last 32 bytes.
with `abi.encode`, you change the address into a 32-byte element.
You solution will still work (since the last 20 bytes are still the address) but will needlessly copy 12 bytes too many.
Note: our appended data is not a normal parameter: think of dynamic params (bytes, string) that are appended at the end of the param block: they still appear *before* our appended address, so our address is clearly can't be considered "standard parameter" - in fact, there is no way that standard solidity can read it (except an assembly code to read the last 20 bytes, as we do)
