### ISSUE TITLE
Anonymous transaction (Sender - Relay - RelayHub - Recipient)

### ISSUE THREAD

**Issue by timothyckw** [opengsn/gsn#290]
May I know that can gsn support anonymous transaction between **Sender** and **Relay**?  If yes, do you have any ideas, suggestions or reference link?

**Comment by drortirosh** [comment]
transaction are not anonymous: the sender signs them.
However, the sender can be nothing but an address and private-key - it doesn't need to have eth or anything else - and thus you can create anonymous clients.
Note, however, that there is a "payer" contract for each transaction (on GSN1 its the recipient contact, and on GSN2 it is a separate Paymaster contract): that "payer" should decide whether it accepts the payment.
If it is a naive contract that accepts everything, then the paymaster can be exploited to pay for every transaction (until its deposit is depleted)
a more complex paymaster can implement a logic to decide if a given sender is trusted, and refuse to pay otherwise.
