### ISSUE TITLE
Nonce problem when using MetaMask

### ISSUE THREAD

**Issue by vrde** [opengsn/gsn#440]
I'm able to relay a transaction using MetaMask and the relay client. After the transaction lands to the blockchain, I see the following error in my browser console:

```
MetaMask - RPC Error: Internal JSON-RPC error
...
the tx doesn't have the correct nonce. account has nonce of: 13 tx has nonce of: 12
```

If I run another transaction, I get the same error but the nonce offset is now 2.

```
the tx doesn't have the correct nonce. account has nonce of: 15 tx has nonce of: 14
```

I guess I can ignore this error for now because everything seems to work anyway, but I'd like to have your input here.

**Comment by drortirosh** [comment]
sorry for the late response,

Yes, it can be ignored.
The reason for these strange errors is the "trustless" nature of GSN: a client doesn't "trust" The relayer to send the request on chain. that would require the client to wait until the transaction is mined (which might take several blocks), only to find out the relayer attempted to "mute" the client.

Instead, the protocol mandates the relayer returns the submitted transaction to the client, so it can validate its structure, gas-price, signature, etc.
But the client goes further, and put this TX on-chain, just in case the relayer didn't.
This way, the client ensures its request is on-chain.
However, since the relayer didn't try trick the client and put it on-chain by itself, the client sees an error message that the TX is already there.
There are several possible such errors.
We do have a task to "mute" these errors - while keeping client's security intact.
