### ISSUE TITLE
Pay for erc20 tokens

### ISSUE THREAD

**Issue by ClassLike** [opengsn/gsn#680]
Hi, currenctly i'm facing an issue.i want to pay gas for any kind of erc20 token.for example user on my site wants to send USDT to another account and he is out of gas.how can i overcome this problem?
Thank you :)

**Comment by forshtat** [comment]
Hello @ClassLike 
Please use our [Discord](https://discord.com/invite/NXXTCbh58s) to ask for help with integration.

Regarding your question, in order to use GSN the target of a meta-transaction has to be GSN-compatible. As USDT does not support a ['permit' method](https://eips.ethereum.org/EIPS/eip-2612) (signature-based equivalent of 'approve'), unlike DAI or USDC, it cannot be used by users directly.

If appropriate, you could use an approach similar to the sample called [ProxyDeployingPaymaster](https://github.com/opengsn/gsn/blob/master/packages/paymasters/contracts/deployproxy/ProxyDeployingPaymaster.sol).

ProxyDeployingPaymaster is an example of how a Paymaster can deploy a GSN-aware Proxy contract for a user within a GSN transaction, and paying for all that in standard ERC-20 tokens. Note how the proxy is deployed with a CREATE2 and the address of a user proxy must hold ERC-20 tokens before the transaction is initialised. So if you can, for example, drop your ERC-20 token to users' proxies' CREATE2 addresses, this approach will work for you. Also note that the first transaction for a user will both create a Proxy contract and trade tokens on Uniswap, costing quite a bit of gas.
