### ISSUE TITLE
Rejected relayTransaction call with reason: value at index ${ index } unnamed

### ISSUE THREAD

**Issue by numpde** [opengsn/gsn#983]
The issue comes from here:
https://github.com/opengsn/gsn/blob/6c876350d627b867601d28c752caec0af3b2b9be/packages/common/src/LightTruffleContract.ts#L23

This seemed to fix it:
```TypeScript
if (typeof ret.toArray === 'function') { // ethers.js v6 Contract treats all arrays as 'proxy' breaking our 'retype'
    return retypeItem(abiOutput, [...ret]);
}
```

Not opening a PR since I don't really understand what's going on.

**Comment by AgentCosmic** [comment]
Also getting the same error, but didn't try to fix. Have to use EthersV5 with `window.ethereum` for now.

**Comment by viac92** [comment]
same issue

**Comment by forshtat** [comment]
The [LightTruffleContract.ts](https://github.com/opengsn/gsn/blob/6c876350d627b867601d28c752caec0af3b2b9be/packages/common/src/LightTruffleContract.ts#L23) file has been removed completely in the new release (`3.0.0-beta.9`).

Please check it out and tell me if the issue is resolved and if the GSN client library is stable. Thank you!

**Comment by viac92** [comment]
Now it's working, thank you!
